version: '3.7'
services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - 80
    networks:
      default:
      buoy:
        aliases:
          - exp-p5js-game-of-life
networks:
  buoy:
    external:
      name: buoy
